openapi: 3.0.0
info:
  title: banking-api-doc
  version: 1.0.0
servers:
  - url: http://{{local_base_url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /api/secure/cachr/register:
    post:
      tags:
        - default
      summary: SignUp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: required
                email: require, Unique
                password: required, at least 6 characters
                role: >-
                  [OPTIONAL] - Only for admin users. Valid value is cachier.
                  Default customer 
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/login:
    post:
      tags:
        - default
      summary: SignIn
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: required
                password: required
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/secure/cust/logout:
    post:
      tags:
        - default
      summary: Logout
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/secure/cust/refresh:
    post:
      tags:
        - default
      summary: RefreshToken
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/secure/cust/account/create:
    post:
      tags:
        - default
      summary: CreateAccount
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                type: 'required. Valid: [savings, current]'
                initialDeposit: 10000
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/secure/admin/account/status-change:
    patch:
      tags:
        - default
      summary: ChangeAccountStatus
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountId: 8
                status: valid values [blocked, pending, approved]
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/secure/cust/account/balance/get:
    get:
      tags:
        - default
      summary: GetMyBalance
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/secure/cachr/account/{accountId}/balance/get:
    get:
      tags:
        - default
      summary: GetAccountBalance
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
        - name: accountId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/secure/cust/transaction/initiate:
    post:
      tags:
        - default
      summary: InitiateTransaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                transactionType: 'Valid Values: [withdrawal, deposit, transfer]'
                accountId: 2
                amount: 5000
                toAccountNumber: >-
                  [OPTIONAL] if it is tranfer enter the account_number eg
                  CUS.13567 to which you wish to send the money
                transferMotive: '[OPTIONAL] if it is tranfer eg For nothing'
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/secure/cust/account/transfers:
    get:
      tags:
        - default
      summary: GetMyTransfers
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/secure/cachr/account/{accountId}/transfers:
    get:
      tags:
        - default
      summary: GetAccountTransfers
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
        - name: accountId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
